FROM node:20-alpine

WORKDIR /app

COPY client/package*.json ./
RUN npm install

COPY client ./

ARG API_URL=http://localhost:3001
ENV VITE_API_URL=$API_URL

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
